### ISSUE TITLE
Download doesnt start

### ISSUE THREAD

**Issue by horphi0815** [xXGuhuXx/auto-yt-dl#4]
Hi,

i added a channel and the video download list has been created, but no download starts...
Is there something i missed?

Runs as Docker on Unraid.

Best regards

**Comment by xXGuhuXx** [comment]
Do you mean that it does not download old videos from the YouTube Channel?
At the moment the dicker is intended only to download new videos.

The list which is created is only used to recognize new videos from the Channel.

**Comment by xXGuhuXx** [comment]
> 
> 
> Do you mean that it does not download old videos from the YouTube Channel?
> At the moment the docker is intended only to download new videos.
> 
> The list which is created is only used to recognize new videos from the Channel.

**Comment by xXGuhuXx** [comment]
welp I closed this by accident. If you want to download all videos, you could delete all links from the Channel.txt in appdata.
However I did not test this.

**Comment by horphi0815** [comment]
> welp I closed this by accident. If you want to download all videos, you could delete all links from the Channel.txt in appdata.
> However I did not test this.

Looks quite good.
He directly started to download and added the downloaded to the txt file.

Which quality will be selected? Almost highest?

BR

**Comment by xXGuhuXx** [comment]
https://github.com/xXGuhuXx/auto-yt-dl/blob/2d3bb0fa2a912525b5cc6214a8f1cc751855f20b/pytubDef/__init__.py#L71

The docker will always try to get the best resolution
