### ISSUE TITLE
CHannelfolder won-t be created

### ISSUE THREAD

**Issue by horphi0815** [xXGuhuXx/auto-yt-dl#6]
https://github.com/xXGuhuXx/auto-yt-dl/blob/2d3bb0fa2a912525b5cc6214a8f1cc751855f20b/pytubDef/__init__.py#L144

**Comment by xXGuhuXx** [comment]
> 
> 
> https://github.com/xXGuhuXx/auto-yt-dl/blob/2d3bb0fa2a912525b5cc6214a8f1cc751855f20b/pytubDef/__init__.py#L144

This def is not supposed to create a channel folder. The Channel directory will be created when the first video starts downloading. The list of URLs will still be stored in /data (/appdata/auto-yt-dl)

**Comment by horphi0815** [comment]
Thank you, the update fixed the Folder creation. :-)
