### ISSUE TITLE
No downloads

### ISSUE THREAD

**Issue by mearl72** [xXGuhuXx/auto-yt-dl#7]
I've added several channels to download. I see the archive text files and the monitoredChannels.txt file in the config folder but I'm not seeing new videos being downloaded into my downloads directory.

I also see that the new video URLs are being appended to the archive text files so I wonder if those are getting added before downloading? I even tried removing the last line. It just got added later still with no video in the downloads directory.

I'm running on Unraid 6.9.2

**Comment by xXGuhuXx** [comment]
Do you mean that it does not download old videos from the YouTube Channel?
At the moment the docker is intended only to download new uploaded videos.

The list which is created is only used to recognize new videos from the Channel.

If you want to download the whole channel, you could just delete every URL from the Channel.txt and the download should start at the next interval.

**Comment by mearl72** [comment]
I do mean it doesn't download the newest videos.

I've had it running for over a day with several YouTube channels (many that post one video every day) and I don't see any videos in my download directory. But I do see the archive file each channel getting updated with their new video's URL as if it was downloaded.

**Comment by xXGuhuXx** [comment]
Ok. Could it be that the videos were live-streamed or used the premier feature of YT? Is there anything of interest in the logs?

**Comment by mearl72** [comment]
So a video did show up all of a sudden. Just one now. I'm not sure why. It looks like another channel just uploaded a video so I'm waiting at least 30 minutes to see if it grabs it. Might of just been a fluke. I'll report back.

I don't follow any premium content (as far as I know. I don't pay for YT). And I didn't expect live streams to download.

I didn't see anything funny in the logs. I'm not sure much is even posted to the logs to be honest. Just looks like start up info last line being.

**Comment by mearl72** [comment]
yeah, it appears to be downloading now. I'm not sure why it wasn't at first.
