### ISSUE TITLE
[Request] Support for Playlists

### ISSUE THREAD

**Issue by CDeLeon94** [xXGuhuXx/auto-yt-dl#9]
Pytube has some support for playlists already, it'd be great if this cool could incorporate a way of monitoring and automatically downloading content published to a playlist. 

Usecase: Channels with tons of content, but only wanting to download a specific subset that is put into topic/series-based playlists. 

If I find some time, I'll see if I can put together a pull for this. But thought I'd just put this out there in the meantime.

**Comment by xXGuhuXx** [comment]
I updated the experimental branch to implement playlist. I will have to test it more till I will update the latest branch but you´re welcome to test it yourself.
